version: '3.5'
services:
  app:
    build: ./docker/php
    restart: "on-failure:5"
    volumes:
      - .:/app:cached
   #  - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
   #  - ./docker/app-entrypoint.sh:/app-entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_USERNAME=user
      - DB_DATABASE=database
      - DB_PASSWORD=password
   #env_file: .env
    depends_on:
      - db
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - .:/app:cached
  #   - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    restart: "on-failure:5"
    depends_on:
      - app
  db:
    image: "mariadb:10.1.38"
    restart: "on-failure:5"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
  redis:
    image: "redis:alpine"
    restart: "on-failure:5"

volumes:
  db:
